export const aptlyData = {
  meta: {
    slug: "aptly",
    number: "02",
    name: "APTLY",
    subtitle: "EXPLAINABLE JOB ELIGIBILITY & ATS ASSISTANT",
    category: "EXPLAINABLE AI & EVALUATION SYSTEMS",
    timeline: "2025",
    status: "INDEPENDENT SYSTEM / COMPLETED",
    links: {
      github: "https://github.com/vedii-codezz/aptly",
      live: "https://aptly-chi.vercel.app/",
    },
    coordinates: [
      { label: "PROJECT TYPE", value: "INDEPENDENT SYSTEM" },
      { label: "STACK CORE", value: "NEXT.JS / TYPESCRIPT" },
      { label: "CORE LOGIC", value: "EXPLAINABLE ELIGIBILITY" },
      { label: "DECISION ENGINE", value: "DETERMINISTIC DECISION CORE" },
    ],
  },

  hero: {
    headline: [
      "ELIGIBILITY ISN'T A NUMBER.",
      "IT'S A CHAIN OF EVIDENCE.",
    ],
    supportingPrinciple: "THE MODEL INTERPRETS. THE ENGINE DECIDES.",
    summary:
      "A forensic technical dossier and ATS diagnostic engine that decomposes unstructured job postings into atomic criteria, evaluates candidate qualifications through deterministic evidence chains, and produces concrete gap remediation plans.",
  },

  illusion: {
    eyebrow: "01 / THE ILLUSION OF THE SCORE",
    heading: "The Breakdown of Opaque Match Metrics",
    annotation: "THE REDUCTIVE SCORING PROBLEM",
    abstractScore: "72%",
    scoreNotice: "ILLUSTRATIVE CONVENTIONAL METRIC // NOT GENERATED BY APTLY",
    questions: [
      { q: "WHY 72?", context: "What formula produced this specific number?" },
      { q: "WHAT MATCHED?", context: "Which technical criteria were confirmed as satisfied?" },
      { q: "WHAT FAILED?", context: "Which specific constraints resulted in disqualification?" },
      { q: "WHAT IS UNKNOWN?", context: "Which items were simply absent from candidate data?" },
      { q: "WHAT CAN I IMPROVE?", context: "How does a candidate take action on a percentage?" },
    ],
    critique: [
      "Conventional recruiting tools and candidate checkers collapse multidimensional qualification data into an arbitrary percentage. A 72% match tells a candidate nothing about whether they failed a hard statutory requirement or merely missed an optional bonus keyword.",
      "A number without evidence is not explainability. When automated filters reject applicants without verifiable provenance, candidates are forced to guess, often resulting in counterproductive resume keyword stuffing. Aptly rejects arbitrary scoring in favor of inspectable, rule-by-rule provenance.",
    ],
  },

  decomposition: {
    eyebrow: "02 / ATOMIC DECOMPOSITION",
    heading: "From Recruiter Prose to Structured Criteria",
    annotation: "UNSTRUCTURED TO TYPED SCHEMA",
    intro:
      "Job descriptions are notoriously noisy documents: aspirational recruiter rhetoric, mandatory requirements, and cultural fluff are blended into unstructured paragraphs. The system uses structured schema extraction to isolate discrete criteria.",
    rawExcerpt: {
      source: "Sample Job Specification // Software Engineer (Full-Stack)",
      text: "We are seeking a proactive Full-Stack Engineer to join our core product team. Candidates must possess a B.Tech/M.Tech graduating in 2024 or 2025 with a minimum 7.5 CGPA / 75% equivalent. Strong hands-on proficiency in Next.js, TypeScript, and Docker containerization is required. Experience with distributed message brokers like Kafka or RabbitMQ is preferred. Role requires physical presence in our Bangalore office.",
    },
    categories: [
      { name: "GRADUATION", desc: "Graduation cohort year or permissible time window" },
      { name: "GPA", desc: "Minimum academic cutoff or percentage threshold" },
      { name: "EDUCATION", desc: "Degree type, major, or accredited institutional criteria" },
      { name: "LOCATION", desc: "Physical residency, hybrid cadence, or relocation criteria" },
      { name: "SKILL", desc: "Specific technologies, languages, tools, or runtimes" },
      { name: "EXPERIENCE", desc: "Years of practice, scope of responsibility, or domain work" },
      { name: "DOCUMENT", desc: "Specific portfolio links, certifications, or transcripts" },
      { name: "OTHER", desc: "Statutory work authorization, security clearances, or shift hours" },
    ],
    importanceTiers: [
      { tier: "MANDATORY", role: "Hard constraint. Failure prevents application eligibility." },
      { tier: "PREFERRED", role: "Competitive advantage. Absence does not disqualify." },
      { tier: "BONUS", role: "Supplementary qualification. Increases evidence depth." },
      { tier: "INFORMATIONAL", role: "Contextual detail (e.g. company mission). Not evaluated." },
    ],
    ambiguityPreservation:
      "Vague recruiter phrasing is flagged rather than assumed to be a hard blocker. If a post says 'familiarity with cloud environments is helpful', the extractor classifies it as PREFERRED / SKILL rather than creating an artificial disqualifier.",
  },

  quadState: {
    eyebrow: "03 / THE QUAD-STATE MODEL",
    heading: "Unknown is a First-Class State",
    annotation: "FOUR-STATE EVALUATION MATRIX",
    thesis: "UNKNOWN ≠ FAILED",
    rationale:
      "Traditional binary screening equates missing resume information with affirmative failure. If a candidate does not explicitly write their high school location or secondary framework, a binary evaluator flags them as disqualified. Aptly introduces a deterministic four-state evaluation model.",
    states: [
      {
        id: "MATCHED",
        label: "MATCHED",
        symbol: "●",
        meaning: "Evidence satisfies requirement",
        criteria: "Candidate submitted data provides verifiable provenance meeting or exceeding the requirement threshold.",
        example: "CGPA 8.42 satisfies the minimum 7.50 cutoff.",
        disposition: "Hard constraint satisfied; entered into verified qualification dossier.",
      },
      {
        id: "PARTIAL",
        label: "PARTIAL",
        symbol: "◑",
        meaning: "Some evidence exists, but is incomplete",
        criteria: "Candidate demonstrates relevant foundation or adjacent exposure, but falls short of exact specification.",
        example: "Docker used in local academic projects; missing production CI/CD deployment experience.",
        disposition: "Surfaced as an actionable candidate improvement point.",
      },
      {
        id: "FAILED",
        label: "FAILED",
        symbol: "✕",
        meaning: "Explicit deterministic contradiction exists",
        criteria: "Candidate data affirmatively breaches a non-negotiable rule or statutory threshold.",
        example: "Graduation year 2022 when job strictly mandates 2024 or 2025 cohort.",
        disposition: "Hard structural blocker triggered; classified as non-actionable constraint.",
      },
      {
        id: "UNKNOWN",
        label: "UNKNOWN",
        symbol: "?",
        meaning: "Candidate data is insufficient",
        criteria: "Resume or profile neither confirms nor refutes the requirement.",
        example: "Job requires on-site presence in Bangalore; resume does not list location or relocation willingness.",
        disposition: "Prompts candidate clarification instead of false disqualification.",
      },
    ],
  },

  evidenceChain: {
    eyebrow: "04 / THE EVIDENCE CHAIN",
    heading: "Forensic Provenance Across Four Stages",
    annotation: "PRIMARY SIGNATURE INSTRUMENT",
    description:
      "Every evaluation is grounded in an end-to-end evidence chain. The model never issues unilateral verdicts; instead, it isolates source text, formats typed rules, extracts candidate citations, and runs deterministic logic.",
    stages: [
      { number: "01", name: "SOURCE", desc: "Raw excerpt from job description and candidate resume" },
      { number: "02", name: "NORMALIZED RULE", desc: "Typed rule expression with strict operator" },
      { number: "03", name: "CANDIDATE EVIDENCE", desc: "Document citation, line offset, and evidence depth" },
      { number: "04", name: "DETERMINISTIC DECISION", desc: "Pure logic output without model hallucination" },
    ],
    traces: [
      {
        id: "GPA",
        label: "ACADEMIC THRESHOLD",
        requirementId: "REQ_GPA_75",
        category: "GPA",
        importance: "MANDATORY",
        stage1Source: {
          jobText: "Minimum 7.5 CGPA (or 75%) across undergraduate coursework.",
          resumeText: "B.Tech in Computer Science & Engineering — Cumulative CGPA: 8.42 / 10.0 (Through Semester 6)",
          documentLocation: "sample_academic_record.pdf [Education Section, Lines 12-14]",
        },
        stage2Rule: {
          expression: "candidate.academic.cgpa >= 7.50",
          operator: ">=",
          targetValue: "7.50 / 10.0",
          ruleType: "NUMERIC_THRESHOLD",
        },
        stage3Evidence: {
          extractedValue: "8.42 / 10.0",
          evidenceStrength: "STRONG",
          strengthRationale: "Direct institutional transcript grade reported with complete grading scale.",
          sourceCount: 1,
        },
        stage4Decision: {
          status: "MATCHED",
          verdict: "8.42 >= 7.50 evaluates to TRUE.",
          explanation: "Mandatory criterion satisfied. Verified arithmetic comparison without model ambiguity.",
        },
      },
      {
        id: "SKILL",
        label: "CONTAINER ORCHESTRATION",
        requirementId: "REQ_SKILL_DOCKER",
        category: "SKILL",
        importance: "MANDATORY",
        stage1Source: {
          jobText: "Hands-on experience with Docker containerization and local dev orchestration.",
          resumeText: "Engineered multi-stage Dockerfiles reducing image size by 42%; orchestrated local dev stack with Docker Compose across 3 microservices.",
          documentLocation: "demonstration_fixture_resume.pdf [Sample Project: Microservices Infrastructure, Lines 34-37]",
        },
        stage2Rule: {
          expression: "candidate.skills.docker.demonstrated_sources.length >= 1",
          operator: ">=",
          targetValue: "1 implementation source",
          ruleType: "SOURCE_VERIFIED_MEMBERSHIP",
        },
        stage3Evidence: {
          extractedValue: "2 implementation citations (Demonstration microservices, DevOps CI pipeline)",
          evidenceStrength: "STRONG",
          strengthRationale: "Verified across 2 independent project entries with specific architectural impact metrics.",
          sourceCount: 2,
        },
        stage4Decision: {
          status: "MATCHED",
          verdict: "2 >= 1 evaluates to TRUE.",
          explanation: "Demonstrated implementation depth satisfies mandatory skill criteria.",
        },
      },
      {
        id: "GRADUATION",
        label: "GRADUATION WINDOW",
        requirementId: "REQ_GRAD_2025",
        category: "GRADUATION",
        importance: "MANDATORY",
        stage1Source: {
          jobText: "Targeting 2024 and 2025 graduating cohorts exclusively.",
          resumeText: "Bachelor of Technology, Graduated: June 2022",
          documentLocation: "demonstration_cohort_record.json [Sample Academic History, Line 08]",
        },
        stage2Rule: {
          expression: "candidate.education.graduation_year in [2024, 2025]",
          operator: "IN_SET",
          targetValue: "{ 2024, 2025 }",
          ruleType: "DISCRETE_SET_MEMBERSHIP",
        },
        stage3Evidence: {
          extractedValue: "2022",
          evidenceStrength: "STRONG",
          strengthRationale: "Conclusive completion timestamp present in verified academic history.",
          sourceCount: 1,
        },
        stage4Decision: {
          status: "FAILED",
          verdict: "2022 in [2024, 2025] evaluates to FALSE.",
          explanation: "Explicit deterministic contradiction. Candidate cohort falls outside mandatory recruiting window.",
        },
      },
    ],
    evidenceStrengthLevels: [
      {
        level: "STRONG",
        criterion: ">= 2 supporting implementation projects or academic coursework sources.",
        nature: "High evidence depth with verified concrete usage.",
      },
      {
        level: "MODERATE",
        criterion: "Exactly 1 verified implementation project or coursework citation.",
        nature: "Satisfactory evidence depth with singular demonstration.",
      },
      {
        level: "WEAK",
        criterion: "Claimed in skills keyword list, but 0 implementation projects found.",
        nature: "Superficial mention without corroborating project provenance.",
      },
      {
        level: "NOT_FOUND",
        criterion: "Neither claimed in skills inventory nor demonstrated in projects.",
        nature: "Total absence of evidence in candidate submission.",
      },
    ],
  },

  eligibilityVsCompetitiveness: {
    eyebrow: "05 / ELIGIBILITY VS COMPETITIVENESS",
    heading: "The Distinction Between Binary Gates and Fit Depth",
    annotation: "CONCEPTUAL BOUNDARY",
    left: {
      question: "CAN I APPLY?",
      subtitle: "DETERMINISTIC ELIGIBILITY",
      nature: "Hard statutory & operational constraints",
      principles: [
        "Mandatory graduation year & cohort windows",
        "Minimum institutional GPA / CGPA thresholds",
        "Statutory work authorization & citizenship requirements",
        "Non-negotiable physical residency or relocation criteria",
      ],
      methodology:
        "Evaluated via pure boolean and numeric logic. A single failed mandatory gate disqualifies the application. There is zero room for model leniency or probabilistic soft-grading.",
    },
    right: {
      question: "HOW STRONG IS MY FIT?",
      subtitle: "EVALUATIVE FIT DEPTH",
      nature: "Soft ranking & qualification depth",
      principles: [
        "Depth of practical projects utilizing preferred technologies",
        "System architecture complexity and production scale exposure",
        "Domain relevance and clear technical documentation",
        "Bonus qualifications and supplementary technical artifacts",
      ],
      methodology:
        "Evaluated via evidence strength metrics (Strong / Moderate / Weak). Never compressed into an arbitrary percentage. Competitiveness reflects proof depth, not hiring guarantees.",
    },
    disclaimer:
      "Aptly intentionally separates eligibility from competitiveness. It does not predict interview callbacks or calculate hiring probabilities, which are subject to external market conditions outside the scope of resume verification.",
  },

  gapEngine: {
    eyebrow: "06 / THE ACTIONABLE GAP ENGINE",
    heading: "Separating Fixed Constraints from Actionable Growth",
    annotation: "REMEDIATION ARCHITECTURE",
    scenarios: [
      {
        id: "ACTIONABLE_SKILL",
        title: "Distributed Message Queues (Apache Kafka)",
        classification: "ACTIONABLE GAP",
        requirementCategory: "SKILL // PREFERRED QUALIFICATION",
        currentStatus: "NOT_FOUND in candidate portfolio",
        actionable: true,
        actionPlan: [
          {
            phase: "LEARN",
            action: "Study event-driven publish/subscribe mechanics, partition keys, consumer groups, and offset management.",
          },
          {
            phase: "PRACTICE",
            action: "Run local Kafka broker in Docker Compose; build producer/consumer services in Node.js/Go.",
          },
          {
            phase: "BUILD",
            action: "Integrate asynchronous event streaming into an existing project architecture (e.g. audit log stream).",
          },
          {
            phase: "PROVE",
            action: "Commit code with architecture README diagram; cite specific throughput metrics and schemas in resume.",
          },
        ],
        remediationOutcome: "Transitions candidate evidence from NOT_FOUND to STRONG evidence depth.",
      },
      {
        id: "FIXED_CONSTRAINT",
        title: "Graduation Cohort Window (2025 Batch)",
        classification: "FIXED CONSTRAINT",
        requirementCategory: "GRADUATION // MANDATORY CONSTRAINT",
        currentStatus: "Graduated June 2022 (Cohort 2022)",
        actionable: false,
        statusNotice: "NOT ACTIONABLE // HARD STRUCTURAL BOUNDARY",
        recommendation: "DO NOT FABRICATE RESUME DATA. TARGET MATCHING OPPORTUNITIES.",
        guidance:
          "Immutable constraints cannot be bridged through additional coursework or resume rephrasing. Attempting to bypass hard corporate gating wastes candidate time and risks applicant blacklists. Aptly explicitly recommends reallocating effort toward senior or open-cohort listings.",
      },
    ],
  },

  atsSection: {
    eyebrow: "07 / ATS WITHOUT THE THEATRE",
    heading: "Document Review Over Arbitrary Percentage Gauges",
    annotation: "REALISTIC ATS DIAGNOSTICS",
    intro:
      "Commercial ATS simulators market arbitrary 90%+ scores to anxious job seekers. In reality, enterprise Applicant Tracking Systems (Workday, Taleo, Greenhouse) are deterministic document parsers. They do not calculate proprietary vibe scores; they parse text hierarchies and test boolean filters.",
    checks: [
      {
        name: "SECTION HEADING STANDARDIZATION",
        purpose: "Standard header semantics (Experience, Education, Skills, Projects) readable by standard PDF parsers.",
        status: "PARSED",
      },
      {
        name: "DOCUMENT HIERARCHY & FLOW",
        purpose: "Single-column linear text flow without nested tables, complex text wraps, or rasterized images.",
        status: "VERIFIED",
      },
      {
        name: "PUBLIC LINK INTEGRITY",
        purpose: "Valid HTTPS format checking for GitHub repositories, live deployments, and technical profiles.",
        status: "AUDITED",
      },
      {
        name: "KEYWORD PROXIMITY & CONTEXT",
        purpose: "Target skills positioned adjacent to actionable metrics and tools rather than isolated keyword dumps.",
        status: "EVALUATED",
      },
      {
        name: "ANTI-KEYWORD-STUFFING LOGIC",
        purpose: "Proactive detection of hidden 1pt fonts, transparent text, and ungrounded keyword dumps.",
        status: "ENFORCED",
      },
    ],
    antiStuffingCallout: {
      headline: "THE ANTI-KEYWORD-STUFFING PRINCIPLE",
      rule: "If evidence exists: articulate the skill honestly within project and impact descriptions.\nIf evidence does not exist: DO NOT insert the keyword merely to game automated filters.",
      implication:
        "Keyword stuffing damages candidate credibility during human technical interviews. Aptly directs candidates to build verifiable projects rather than gaming regex patterns.",
    },
  },

  perimeterDefense: {
    eyebrow: "08 / PERIMETER DEFENSE & PRIVACY",
    heading: "Hardened Ingestion and Ephemeral Processing",
    annotation: "SECURITY & DATA BOUNDARIES",
    pipeline: [
      {
        step: "01",
        name: "URL VALIDATION",
        detail: "Strict RFC 3986 protocol check restricting requests exclusively to http:// and https:// schemes.",
      },
      {
        step: "02",
        name: "DNS PRE-RESOLUTION",
        detail: "Pre-fetch DNS resolution checking all A and AAAA records prior to opening socket connections.",
      },
      {
        step: "03",
        name: "PRIVATE NETWORK REJECTION",
        detail: "SSRF firewall blocking RFC 1918 subnets (10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16), loopback (127.0.0.1), and link-local addresses.",
      },
      {
        step: "04",
        name: "STREAMING CEILING (750 KB)",
        detail: "Terminates incoming streams exceeding 750 KB to guard against decompression bombs and server memory starvation.",
      },
    ],
    privacyArchitecture: [
      {
        title: "NO DATABASE IN CURRENT PROTOTYPE",
        detail: "All parsed resumes, job descriptions, and evaluation outputs are maintained solely in ephemeral client-side Zustand state during the active browser session.",
      },
      {
        title: "TRANSIENT INFERENCE PAYLOADS",
        detail: "When AI extraction is invoked, Gemini (gemini-3.7-flash) receives raw text strictly as transient inference payloads. No candidate dossiers are stored or used for model fine-tuning.",
      },
      {
        title: "CLIENT-SIDE MEMORY PARSING",
        detail: "PDF document parsing executes in-memory. Candidate resumes are not saved to persistent server storage or transmitted to analytics providers.",
      },
    ],
  },

  independentEngineering: {
    eyebrow: "09 / INDEPENDENT SYSTEM ENGINEERING",
    heading: "End-to-End Architectural Ownership",
    annotation: "AUTHORSHIP & IMPLEMENTATION",
    author: "Bedantika Mondal",
    summary:
      "Aptly was conceptualized, designed, architected, and implemented independently by Bedantika Mondal. The project represents a complete individual effort across deterministic rule modeling, frontend architecture, and security hardening.",
    commitVerification: "100% solo authorship verified across 14 of 14 repository commits and specification documentation.",
    layers: [
      {
        domain: "ARCHITECTURE & DESIGN",
        work: "Formulated the deterministic-first evaluation framework, quad-state classification model, and actionable gap progression roadmap.",
      },
      {
        domain: "DETERMINISTIC DECISION CORE",
        work: "Authored the complete TypeScript rule engine, academic GPA evaluators, ATS structural diagnostics, and evidence strength algorithms.",
      },
      {
        domain: "PERIMETER DEFENSE & SSRF",
        work: "Engineered the job description URL ingestion gateway with DNS validation, private subnet CIDR blocking, and stream size ceilings.",
      },
      {
        domain: "FRONTEND & PARSER INTEGRATION",
        work: "Built the Next.js App Router interface, interactive evidence inspector, ephemeral session state, and PDF document parsing pipelines.",
      },
    ],
    technologies: [
      { name: "FRAMEWORK", value: "Next.js 15 (App Router)" },
      { name: "LANGUAGE", value: "TypeScript 5 (Strict Mode)" },
      { name: "STYLING", value: "Tailwind CSS" },
      { name: "STATE MANAGEMENT", value: "Zustand (Ephemeral Session Store)" },
      { name: "AI INTEGRATION", value: "Google Gemini API (gemini-3.7-flash via @google/generative-ai)" },
      { name: "SCHEMA VALIDATION", value: "Zod v3" },
      { name: "DOCUMENT EXTRACTION", value: "pdf-parse / unpdf" },
    ],
  },

  retrospective: {
    eyebrow: "10 / RETROSPECTIVE & LESSONS",
    heading: "Architectural Reflections on Evaluation Systems",
    annotation: "ENGINEERING TAKEAWAYS",
    lessons: [
      {
        number: "01",
        title: "UNKNOWN IS A REAL AND NECESSARY STATE",
        body: "Early prototype iterations attempted binary classification: satisfied or failed. But missing resume data is fundamentally different from affirmative contradiction. Treating UNKNOWN as a distinct third dimension prevents unwarranted disqualification and builds candidate trust.",
      },
      {
        number: "02",
        title: "THE MODEL INTERPRETS. THE ENGINE DECIDES.",
        body: "Language models excel at reading messy, poorly phrased job descriptions and normalizing them into typed JSON schemas. However, having an LLM evaluate numeric cutoffs or boolean eligibility invariably invites hallucinations and prompt drift. Splitting extraction from deterministic rule code yields dependable results.",
      },
      {
        number: "03",
        title: "EVIDENCE IS INFINITELY MORE VALUABLE THAN A SCORE",
        body: "Candidates cannot act on an opaque '74%' score. But an inspectable 4-stage provenance chain—showing the exact job sentence, the rule, the resume excerpt, and the comparison result—makes every decision transparent and immediately actionable.",
      },
      {
        number: "04",
        title: "SCRAPING PUBLIC JOB PAGES HAS HARD LIMITS",
        body: "Enterprise job portals (Workday, Greenhouse, Lever) increasingly rely on dynamic client-side rendering and aggressive anti-bot protection. Simple HTTP fetching frequently fails on JavaScript-rendered modals, reinforcing why manual paste fallbacks and SSRF perimeter hardening are critical.",
      },
    ],
  },

  nextProject: {
    index: "11 / NEXT CASE STUDY",
    nextNumber: "03",
    nextName: "VEYRA",
    nextSubtitle: "Spatial Cognitive Interface",
    nextCategory: "EXPERIMENTAL INTERFACE ARCHITECTURE",
  },
} as const;
